export interface ExerciseDefinition {
  name: string;
  description: string;
  exerciseType: 'weighted' | 'bodyweight';
  muscleGroup: string;
  equipment: string[];
  isCompound: boolean;
}

export const MUSCLE_GROUPS = [
  'Chest',
  'Back',
  'Shoulders',
  'Biceps',
  'Triceps',
  'Quadriceps',
  'Hamstrings',
  'Glutes',
  'Calves',
  'Core',
  'Forearms',
] as const;

export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export const DEFAULT_EXERCISES: ExerciseDefinition[] = [
  // Chest
  {
    name: 'Bench Press',
    description: 'Barbell bench press for chest development',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Incline Bench Press',
    description: 'Incline barbell press targeting upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell', 'incline bench'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Bench Press',
    description: 'Dumbbell press for chest with greater range of motion',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbells', 'bench'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Flyes',
    description: 'Isolation exercise for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbells', 'bench'],
    isCompound: false,
  },
  {
    name: 'Push-ups',
    description: 'Classic bodyweight chest exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Chest',
    equipment: [],
    isCompound: true,
  },
  {
    name: 'Cable Crossover',
    description: 'Cable isolation for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['cable machine'],
    isCompound: false,
  },

  // Back
  {
    name: 'Deadlift',
    description: 'Full body compound lift focusing on posterior chain',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Pull-ups',
    description: 'Bodyweight vertical pull for back width',
    exerciseType: 'bodyweight',
    muscleGroup: 'Back',
    equipment: ['pull-up bar'],
    isCompound: true,
  },
  {
    name: 'Chin-ups',
    description: 'Underhand grip pull-up emphasizing biceps',
    exerciseType: 'bodyweight',
    muscleGroup: 'Back',
    equipment: ['pull-up bar'],
    isCompound: true,
  },
  {
    name: 'Barbell Row',
    description: 'Bent over row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Row',
    description: 'Single arm row for unilateral back development',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['dumbbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Lat Pulldown',
    description: 'Cable exercise for lat width',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Seated Cable Row',
    description: 'Cable row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },

  // Shoulders
  {
    name: 'Overhead Press',
    description: 'Standing barbell press for shoulders',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Shoulder Press',
    description: 'Seated or standing dumbbell press',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Lateral Raises',
    description: 'Isolation for lateral deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Front Raises',
    description: 'Isolation for front deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Rear Delt Flyes',
    description: 'Isolation for rear deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Face Pulls',
    description: 'Cable exercise for rear delts and rotator cuff',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['cable machine'],
    isCompound: false,
  },

  // Biceps
  {
    name: 'Barbell Curl',
    description: 'Classic bicep builder',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Dumbbell Curl',
    description: 'Alternating or simultaneous dumbbell curls',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Hammer Curl',
    description: 'Neutral grip curls for brachialis',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Preacher Curl',
    description: 'Isolated bicep curl on preacher bench',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['barbell', 'preacher bench'],
    isCompound: false,
  },

  // Triceps
  {
    name: 'Close Grip Bench Press',
    description: 'Bench press variation emphasizing triceps',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['barbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Tricep Dips',
    description: 'Bodyweight tricep exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Triceps',
    equipment: ['dip bars'],
    isCompound: true,
  },
  {
    name: 'Tricep Pushdown',
    description: 'Cable pushdown for triceps',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Skull Crushers',
    description: 'Lying tricep extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['barbell', 'bench'],
    isCompound: false,
  },
  {
    name: 'Overhead Tricep Extension',
    description: 'Overhead dumbbell or cable extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },

  // Quadriceps
  {
    name: 'Squat',
    description: 'King of leg exercises',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['barbell', 'squat rack'],
    isCompound: true,
  },
  {
    name: 'Front Squat',
    description: 'Quad-dominant squat variation',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['barbell', 'squat rack'],
    isCompound: true,
  },
  {
    name: 'Leg Press',
    description: 'Machine compound leg exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['leg press machine'],
    isCompound: true,
  },
  {
    name: 'Leg Extension',
    description: 'Isolation for quadriceps',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['leg extension machine'],
    isCompound: false,
  },
  {
    name: 'Lunges',
    description: 'Unilateral leg exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Single leg squat with rear foot elevated',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbells', 'bench'],
    isCompound: true,
  },

  // Hamstrings
  {
    name: 'Romanian Deadlift',
    description: 'Hip hinge for hamstrings and glutes',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Leg Curl',
    description: 'Isolation for hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['leg curl machine'],
    isCompound: false,
  },
  {
    name: 'Good Mornings',
    description: 'Barbell hip hinge for posterior chain',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['barbell'],
    isCompound: true,
  },

  // Glutes
  {
    name: 'Hip Thrust',
    description: 'Primary glute builder',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['barbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Glute Bridge',
    description: 'Bodyweight or weighted glute exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Glutes',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Cable Kickback',
    description: 'Cable isolation for glutes',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['cable machine'],
    isCompound: false,
  },

  // Calves
  {
    name: 'Standing Calf Raise',
    description: 'Standing calf raise on machine or smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['calf raise machine'],
    isCompound: false,
  },
  {
    name: 'Seated Calf Raise',
    description: 'Seated calf raise for soleus',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['seated calf machine'],
    isCompound: false,
  },

  // Core
  {
    name: 'Plank',
    description: 'Isometric core stability exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Hanging Leg Raise',
    description: 'Advanced ab exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: ['pull-up bar'],
    isCompound: false,
  },
  {
    name: 'Cable Crunch',
    description: 'Weighted ab exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Ab Wheel Rollout',
    description: 'Dynamic core stability exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: ['ab wheel'],
    isCompound: false,
  },
  {
    name: 'Russian Twist',
    description: 'Rotational core exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
];
