export interface ExerciseDefinition {
  name: string;
  description: string;
  exerciseType: 'weighted' | 'bodyweight';
  muscleGroup: string;
  equipment: string[];
  isCompound: boolean;
}

export const MUSCLE_GROUPS = [
  'Chest',
  'Back',
  'Shoulders',
  'Biceps',
  'Triceps',
  'Quadriceps',
  'Hamstrings',
  'Glutes',
  'Calves',
  'Core',
  'Forearms',
] as const;

export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export const DEFAULT_EXERCISES: ExerciseDefinition[] = [
  // Chest
  {
    name: 'Bench Press',
    description: 'Barbell bench press for chest development',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Bench Press',
    description: 'Dumbbell bench press for chest with greater range of motion',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Decline Bench Press',
    description: 'Barbell press on decline bench for lower chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Incline Bench Press',
    description: 'Incline barbell press targeting upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Incline Bench Press',
    description: 'Incline dumbbell press for upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Chest Press',
    description: 'Machine press for chest development',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Incline Chest Press',
    description: 'Machine incline press for upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Chest Fly',
    description: 'Machine fly for chest isolation',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['machine'],
    isCompound: false,
  },
  {
    name: 'Downward Fly',
    description: 'Downward cable fly for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['machine'],
    isCompound: false,
  },
  {
    name: 'Chest Dip',
    description: 'Assisted dip machine for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Hex Press',
    description: 'Dumbbell hex press for inner chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Landmine Chest Press',
    description: 'Landmine press for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Push-Up',
    description: 'Classic bodyweight chest exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Chest',
    equipment: [],
    isCompound: true,
  },
  {
    name: 'Upward Rip',
    description: 'Upward cable movement for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['cable'],
    isCompound: false,
  },

  // Back
  {
    name: 'Bent-Over Row',
    description: 'Bent over dumbbell row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Bent-Over One-Arm Row',
    description: 'Single arm bent over row for unilateral back development',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Landmine Row',
    description: 'Landmine row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Lat Pulldown',
    description: 'Cable lat pulldown for back width',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable'],
    isCompound: true,
  },
  {
    name: 'Lat Pulldown',
    description: 'Machine lat pulldown for back width',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Lat Pulldown (Single Arm)',
    description: 'Single arm machine lat pulldown',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Lat Pushdown',
    description: 'Straight arm lat pushdown for lats',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable'],
    isCompound: false,
  },
  {
    name: 'One-Arm Row',
    description: 'Single arm cable row for back',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable'],
    isCompound: true,
  },
  {
    name: 'Pull-Up',
    description: 'Bodyweight vertical pull for back width',
    exerciseType: 'bodyweight',
    muscleGroup: 'Back',
    equipment: [],
    isCompound: true,
  },
  {
    name: 'Pulldown',
    description: 'Machine pulldown for back',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Seated Row',
    description: 'Machine seated row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Seated Row',
    description: 'Cable seated row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable'],
    isCompound: true,
  },
  {
    name: 'T-Bar Row',
    description: 'T-bar row machine for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Face Pull',
    description: 'Cable face pull for rear delts and upper back',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable'],
    isCompound: false,
  },
  {
    name: 'Shoulder Shrug',
    description: 'Barbell shrug for traps',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Shrug',
    description: 'Cable shrug for traps',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable'],
    isCompound: false,
  },

  // Shoulders
  {
    name: 'Arnold Press',
    description: 'Rotating dumbbell press for full delt activation',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Front Raise',
    description: 'Dumbbell front raise for front deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Lateral Raise',
    description: 'Dumbbell lateral raise for side deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Overhead Press',
    description: 'Standing barbell press for shoulders',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Overhead Press',
    description: 'Standing or seated dumbbell press',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Shoulder Press',
    description: 'Machine press for shoulders',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Shoulder Press (Single Arm)',
    description: 'Single arm machine shoulder press',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Upright Row',
    description: 'Barbell upright row for shoulders and traps',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['barbell'],
    isCompound: true,
  },

  // Biceps
  {
    name: 'Bicep Curl',
    description: 'Classic barbell bicep curl',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Bicep Curl',
    description: 'Cable bicep curl',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['cable'],
    isCompound: false,
  },
  {
    name: 'Bicep Curl',
    description: 'Dumbbell bicep curl',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Bicep Curl',
    description: 'Machine bicep curl',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['machine'],
    isCompound: false,
  },
  {
    name: 'Concentration Curl',
    description: 'Seated single arm concentration curl',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Hammer Curl',
    description: 'Neutral grip dumbbell curl for brachialis',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Incline Curl',
    description: 'Incline bench dumbbell curl for long head stretch',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Preacher Curl',
    description: 'Barbell preacher curl for bicep isolation',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Preacher Curl',
    description: 'Machine preacher curl for bicep isolation',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['machine'],
    isCompound: false,
  },

  // Triceps
  {
    name: 'Close Grip Bench Press',
    description: 'Close grip bench press for triceps',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Overhead Tricep Extension',
    description: 'Overhead cable extension for triceps long head',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable'],
    isCompound: false,
  },
  {
    name: 'Skull Crusher',
    description: 'Lying barbell tricep extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Skull Crusher',
    description: 'Lying dumbbell tricep extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Triceps Extension',
    description: 'Machine tricep extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['machine'],
    isCompound: false,
  },
  {
    name: 'Triceps Pushdown',
    description: 'Cable tricep pushdown',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable'],
    isCompound: false,
  },

  // Quadriceps
  {
    name: 'Front Squat',
    description: 'Front loaded barbell squat for quad emphasis',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Leg Extension',
    description: 'Machine leg extension for quad isolation',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['machine'],
    isCompound: false,
  },
  {
    name: 'Leg Press',
    description: 'Machine leg press for legs',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['machine'],
    isCompound: true,
  },
  {
    name: 'Squat',
    description: 'Barbell back squat for legs',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Squat',
    description: 'Machine squat for legs',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['machine'],
    isCompound: true,
  },

  // Hamstrings
  {
    name: 'Leg Curl',
    description: 'Machine leg curl for hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['machine'],
    isCompound: false,
  },

  // Core
  {
    name: 'Crunch',
    description: 'Machine crunch for abs',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['machine'],
    isCompound: false,
  },

  // Forearms
  {
    name: 'Reverse Curl',
    description: 'Overhand grip barbell curl for forearms',
    exerciseType: 'weighted',
    muscleGroup: 'Forearms',
    equipment: ['barbell'],
    isCompound: false,
  },
];
