export interface ExerciseDefinition {
  name: string;
  description: string;
  exerciseType: 'weighted' | 'bodyweight';
  muscleGroup: string;
  equipment: string[];
  isCompound: boolean;
}

export const MUSCLE_GROUPS = [
  'Chest',
  'Back',
  'Shoulders',
  'Biceps',
  'Triceps',
  'Quadriceps',
  'Hamstrings',
  'Glutes',
  'Calves',
  'Core',
  'Forearms',
] as const;

export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export const DEFAULT_EXERCISES: ExerciseDefinition[] = [
  // Chest
  {
    name: 'Bench Press',
    description: 'Barbell bench press for chest development',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Incline Bench Press',
    description: 'Incline barbell press targeting upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['barbell', 'incline bench'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Bench Press',
    description: 'Dumbbell press for chest with greater range of motion',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbells', 'bench'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Flyes',
    description: 'Isolation exercise for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['dumbbells', 'bench'],
    isCompound: false,
  },
  {
    name: 'Push-ups',
    description: 'Classic bodyweight chest exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Chest',
    equipment: [],
    isCompound: true,
  },
  {
    name: 'Cable Crossover',
    description: 'Cable isolation for chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Chest Press Machine',
    description: 'Machine press for chest development',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['chest press machine'],
    isCompound: true,
  },
  {
    name: 'Incline Chest Press Machine',
    description: 'Machine incline press for upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['incline chest press machine'],
    isCompound: true,
  },
  {
    name: 'Pec Deck',
    description: 'Machine fly for chest isolation',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['pec deck machine'],
    isCompound: false,
  },
  {
    name: 'Smith Machine Bench Press',
    description: 'Guided barbell bench press',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['smith machine'],
    isCompound: true,
  },
  {
    name: 'Smith Machine Incline Press',
    description: 'Guided incline press on smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['smith machine'],
    isCompound: true,
  },
  {
    name: 'Low Cable Fly',
    description: 'Cable fly from low position for upper chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'High Cable Fly',
    description: 'Cable fly from high position for lower chest',
    exerciseType: 'weighted',
    muscleGroup: 'Chest',
    equipment: ['cable machine'],
    isCompound: false,
  },

  // Back
  {
    name: 'Deadlift',
    description: 'Full body compound lift focusing on posterior chain',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Pull-ups',
    description: 'Bodyweight vertical pull for back width',
    exerciseType: 'bodyweight',
    muscleGroup: 'Back',
    equipment: ['pull-up bar'],
    isCompound: true,
  },
  {
    name: 'Chin-ups',
    description: 'Underhand grip pull-up emphasizing biceps',
    exerciseType: 'bodyweight',
    muscleGroup: 'Back',
    equipment: ['pull-up bar'],
    isCompound: true,
  },
  {
    name: 'Barbell Row',
    description: 'Bent over row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Row',
    description: 'Single arm row for unilateral back development',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['dumbbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Lat Pulldown',
    description: 'Cable exercise for lat width',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Seated Cable Row',
    description: 'Cable row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'T-Bar Row',
    description: 'Landmine row for back thickness',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['t-bar row machine'],
    isCompound: true,
  },
  {
    name: 'Assisted Pull-up Machine',
    description: 'Counterweight assisted pull-ups',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['assisted pull-up machine'],
    isCompound: true,
  },
  {
    name: 'Plate Loaded Row',
    description: 'Plate loaded seated row machine',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['plate loaded row machine'],
    isCompound: true,
  },
  {
    name: 'Close Grip Lat Pulldown',
    description: 'Lat pulldown with close grip for inner back',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Wide Grip Lat Pulldown',
    description: 'Lat pulldown with wide grip for lat width',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Straight Arm Pulldown',
    description: 'Cable pulldown with straight arms for lats',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Reverse Grip Lat Pulldown',
    description: 'Underhand grip lat pulldown',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Single Arm Cable Row',
    description: 'Unilateral cable row for back',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Chest Supported Row',
    description: 'Incline bench dumbbell row',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['dumbbells', 'incline bench'],
    isCompound: true,
  },
  {
    name: 'Plate Loaded High Row',
    description: 'High row machine for upper back',
    exerciseType: 'weighted',
    muscleGroup: 'Back',
    equipment: ['high row machine'],
    isCompound: true,
  },
  {
    name: 'Back Extension',
    description: 'Hyperextension for lower back',
    exerciseType: 'bodyweight',
    muscleGroup: 'Back',
    equipment: ['back extension bench'],
    isCompound: false,
  },

  // Shoulders
  {
    name: 'Overhead Press',
    description: 'Standing barbell press for shoulders',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Shoulder Press',
    description: 'Seated or standing dumbbell press',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Lateral Raises',
    description: 'Isolation for lateral deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Front Raises',
    description: 'Isolation for front deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Rear Delt Flyes',
    description: 'Isolation for rear deltoids',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Face Pulls',
    description: 'Cable exercise for rear delts and rotator cuff',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Shoulder Press Machine',
    description: 'Machine press for shoulders',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['shoulder press machine'],
    isCompound: true,
  },
  {
    name: 'Smith Machine Shoulder Press',
    description: 'Guided shoulder press on smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['smith machine'],
    isCompound: true,
  },
  {
    name: 'Lateral Raise Machine',
    description: 'Machine lateral raises for side delts',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['lateral raise machine'],
    isCompound: false,
  },
  {
    name: 'Rear Delt Machine',
    description: 'Reverse pec deck for rear delts',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['rear delt machine'],
    isCompound: false,
  },
  {
    name: 'Cable Lateral Raise',
    description: 'Cable lateral raise for side delts',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Cable Front Raise',
    description: 'Cable front raise for front delts',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Arnold Press',
    description: 'Rotating dumbbell press for full delt activation',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Upright Row',
    description: 'Barbell or cable row for shoulders and traps',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Shrugs',
    description: 'Trap isolation with dumbbells or barbell',
    exerciseType: 'weighted',
    muscleGroup: 'Shoulders',
    equipment: ['dumbbells'],
    isCompound: false,
  },

  // Biceps
  {
    name: 'Barbell Curl',
    description: 'Classic bicep builder',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Dumbbell Curl',
    description: 'Alternating or simultaneous dumbbell curls',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Hammer Curl',
    description: 'Neutral grip curls for brachialis',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbells'],
    isCompound: false,
  },
  {
    name: 'Preacher Curl',
    description: 'Isolated bicep curl on preacher bench',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['barbell', 'preacher bench'],
    isCompound: false,
  },
  {
    name: 'Cable Curl',
    description: 'Bicep curl on cable machine',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Bicep Curl Machine',
    description: 'Machine curl for biceps',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['bicep curl machine'],
    isCompound: false,
  },
  {
    name: 'Concentration Curl',
    description: 'Seated single arm curl for bicep peak',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Incline Dumbbell Curl',
    description: 'Curls on incline bench for long head stretch',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbells', 'incline bench'],
    isCompound: false,
  },
  {
    name: 'Spider Curl',
    description: 'Curls on preacher bench reverse side',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['dumbbells', 'preacher bench'],
    isCompound: false,
  },
  {
    name: 'EZ Bar Curl',
    description: 'Curl with cambered bar for wrist comfort',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['ez bar'],
    isCompound: false,
  },
  {
    name: 'Rope Hammer Curl',
    description: 'Cable hammer curl with rope attachment',
    exerciseType: 'weighted',
    muscleGroup: 'Biceps',
    equipment: ['cable machine'],
    isCompound: false,
  },

  // Triceps
  {
    name: 'Close Grip Bench Press',
    description: 'Bench press variation emphasizing triceps',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['barbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Tricep Dips',
    description: 'Bodyweight tricep exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Triceps',
    equipment: ['dip bars'],
    isCompound: true,
  },
  {
    name: 'Tricep Pushdown',
    description: 'Cable pushdown for triceps',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Skull Crushers',
    description: 'Lying tricep extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['barbell', 'bench'],
    isCompound: false,
  },
  {
    name: 'Overhead Tricep Extension',
    description: 'Overhead dumbbell or cable extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Tricep Extension Machine',
    description: 'Machine tricep extension',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['tricep extension machine'],
    isCompound: false,
  },
  {
    name: 'Rope Tricep Pushdown',
    description: 'Cable pushdown with rope attachment',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Single Arm Tricep Pushdown',
    description: 'Unilateral cable pushdown',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Overhead Cable Extension',
    description: 'Cable extension overhead for long head',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Tricep Kickback',
    description: 'Dumbbell kickback for triceps',
    exerciseType: 'weighted',
    muscleGroup: 'Triceps',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Diamond Push-ups',
    description: 'Close hand push-ups for triceps',
    exerciseType: 'bodyweight',
    muscleGroup: 'Triceps',
    equipment: [],
    isCompound: true,
  },
  {
    name: 'Bench Dips',
    description: 'Dips using a bench for triceps',
    exerciseType: 'bodyweight',
    muscleGroup: 'Triceps',
    equipment: ['bench'],
    isCompound: true,
  },

  // Quadriceps
  {
    name: 'Squat',
    description: 'King of leg exercises',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['barbell', 'squat rack'],
    isCompound: true,
  },
  {
    name: 'Front Squat',
    description: 'Quad-dominant squat variation',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['barbell', 'squat rack'],
    isCompound: true,
  },
  {
    name: 'Leg Press',
    description: 'Machine compound leg exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['leg press machine'],
    isCompound: true,
  },
  {
    name: 'Leg Extension',
    description: 'Isolation for quadriceps',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['leg extension machine'],
    isCompound: false,
  },
  {
    name: 'Lunges',
    description: 'Unilateral leg exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Single leg squat with rear foot elevated',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbells', 'bench'],
    isCompound: true,
  },
  {
    name: 'Hack Squat',
    description: 'Machine squat for quad emphasis',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['hack squat machine'],
    isCompound: true,
  },
  {
    name: 'Smith Machine Squat',
    description: 'Guided squat on smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['smith machine'],
    isCompound: true,
  },
  {
    name: 'Pendulum Squat',
    description: 'Pendulum machine squat for quads',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['pendulum squat machine'],
    isCompound: true,
  },
  {
    name: 'V-Squat',
    description: 'V-squat machine for quad development',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['v-squat machine'],
    isCompound: true,
  },
  {
    name: 'Sissy Squat',
    description: 'Bodyweight or assisted squat for quad isolation',
    exerciseType: 'bodyweight',
    muscleGroup: 'Quadriceps',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Goblet Squat',
    description: 'Dumbbell or kettlebell front squat',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Walking Lunges',
    description: 'Dynamic lunges across the floor',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Step Ups',
    description: 'Step up onto platform for legs',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['dumbbells', 'platform'],
    isCompound: true,
  },
  {
    name: 'Single Leg Press',
    description: 'Unilateral leg press',
    exerciseType: 'weighted',
    muscleGroup: 'Quadriceps',
    equipment: ['leg press machine'],
    isCompound: true,
  },

  // Hamstrings
  {
    name: 'Romanian Deadlift',
    description: 'Hip hinge for hamstrings and glutes',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Leg Curl',
    description: 'Isolation for hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['leg curl machine'],
    isCompound: false,
  },
  {
    name: 'Good Mornings',
    description: 'Barbell hip hinge for posterior chain',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Lying Leg Curl',
    description: 'Lying machine curl for hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['lying leg curl machine'],
    isCompound: false,
  },
  {
    name: 'Seated Leg Curl',
    description: 'Seated machine curl for hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['seated leg curl machine'],
    isCompound: false,
  },
  {
    name: 'Stiff Leg Deadlift',
    description: 'Straight leg deadlift for hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    description: 'RDL with dumbbells',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Single Leg Romanian Deadlift',
    description: 'Unilateral RDL for balance and hamstrings',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['dumbbell'],
    isCompound: true,
  },
  {
    name: 'Nordic Hamstring Curl',
    description: 'Eccentric bodyweight hamstring exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Hamstrings',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Cable Pull Through',
    description: 'Cable hip hinge for hamstrings and glutes',
    exerciseType: 'weighted',
    muscleGroup: 'Hamstrings',
    equipment: ['cable machine'],
    isCompound: true,
  },

  // Glutes
  {
    name: 'Hip Thrust',
    description: 'Primary glute builder',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['barbell', 'bench'],
    isCompound: true,
  },
  {
    name: 'Glute Bridge',
    description: 'Bodyweight or weighted glute exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Glutes',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Cable Kickback',
    description: 'Cable isolation for glutes',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Glute Kickback Machine',
    description: 'Machine glute kickback',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['glute kickback machine'],
    isCompound: false,
  },
  {
    name: 'Hip Abductor Machine',
    description: 'Machine for outer hip and glutes',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['hip abductor machine'],
    isCompound: false,
  },
  {
    name: 'Hip Adductor Machine',
    description: 'Machine for inner thigh',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['hip adductor machine'],
    isCompound: false,
  },
  {
    name: 'Smith Machine Hip Thrust',
    description: 'Hip thrust using smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['smith machine', 'bench'],
    isCompound: true,
  },
  {
    name: 'Single Leg Hip Thrust',
    description: 'Unilateral hip thrust',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['bench'],
    isCompound: false,
  },
  {
    name: 'Frog Pumps',
    description: 'Glute activation with feet together',
    exerciseType: 'bodyweight',
    muscleGroup: 'Glutes',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Sumo Deadlift',
    description: 'Wide stance deadlift for glutes and inner thigh',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['barbell'],
    isCompound: true,
  },
  {
    name: 'Reverse Lunges',
    description: 'Step back lunges for glutes emphasis',
    exerciseType: 'weighted',
    muscleGroup: 'Glutes',
    equipment: ['dumbbells'],
    isCompound: true,
  },

  // Calves
  {
    name: 'Standing Calf Raise',
    description: 'Standing calf raise on machine or smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['calf raise machine'],
    isCompound: false,
  },
  {
    name: 'Seated Calf Raise',
    description: 'Seated calf raise for soleus',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['seated calf machine'],
    isCompound: false,
  },
  {
    name: 'Leg Press Calf Raise',
    description: 'Calf raise on leg press machine',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['leg press machine'],
    isCompound: false,
  },
  {
    name: 'Smith Machine Calf Raise',
    description: 'Standing calf raise on smith machine',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['smith machine'],
    isCompound: false,
  },
  {
    name: 'Donkey Calf Raise',
    description: 'Bent over calf raise for stretch',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['calf raise machine'],
    isCompound: false,
  },
  {
    name: 'Single Leg Calf Raise',
    description: 'Unilateral calf raise',
    exerciseType: 'weighted',
    muscleGroup: 'Calves',
    equipment: ['dumbbell'],
    isCompound: false,
  },

  // Core
  {
    name: 'Plank',
    description: 'Isometric core stability exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Hanging Leg Raise',
    description: 'Advanced ab exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: ['pull-up bar'],
    isCompound: false,
  },
  {
    name: 'Cable Crunch',
    description: 'Weighted ab exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Ab Wheel Rollout',
    description: 'Dynamic core stability exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: ['ab wheel'],
    isCompound: false,
  },
  {
    name: 'Russian Twist',
    description: 'Rotational core exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Ab Crunch Machine',
    description: 'Machine crunch for abs',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['ab crunch machine'],
    isCompound: false,
  },
  {
    name: 'Torso Rotation Machine',
    description: 'Machine for obliques',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['torso rotation machine'],
    isCompound: false,
  },
  {
    name: 'Woodchoppers',
    description: 'Cable rotational movement for obliques',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['cable machine'],
    isCompound: true,
  },
  {
    name: 'Dead Bug',
    description: 'Core stability exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Bird Dog',
    description: 'Core and back stability exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Mountain Climbers',
    description: 'Dynamic core exercise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: true,
  },
  {
    name: 'Bicycle Crunches',
    description: 'Rotational crunch for obliques',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Decline Sit-ups',
    description: 'Sit-ups on decline bench',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: ['decline bench'],
    isCompound: false,
  },
  {
    name: 'V-Ups',
    description: 'Full body crunch touching toes',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Pallof Press',
    description: 'Anti-rotation cable exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Core',
    equipment: ['cable machine'],
    isCompound: false,
  },
  {
    name: 'Reverse Crunch',
    description: 'Lower ab focused crunch',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: [],
    isCompound: false,
  },
  {
    name: 'Knee Raise',
    description: 'Hanging or captain chair knee raise',
    exerciseType: 'bodyweight',
    muscleGroup: 'Core',
    equipment: ['pull-up bar'],
    isCompound: false,
  },

  // Forearms
  {
    name: 'Wrist Curl',
    description: 'Forearm flexor exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Forearms',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Reverse Wrist Curl',
    description: 'Forearm extensor exercise',
    exerciseType: 'weighted',
    muscleGroup: 'Forearms',
    equipment: ['dumbbell'],
    isCompound: false,
  },
  {
    name: 'Farmers Walk',
    description: 'Loaded carry for grip and forearms',
    exerciseType: 'weighted',
    muscleGroup: 'Forearms',
    equipment: ['dumbbells'],
    isCompound: true,
  },
  {
    name: 'Reverse Curl',
    description: 'Overhand grip curl for forearms',
    exerciseType: 'weighted',
    muscleGroup: 'Forearms',
    equipment: ['barbell'],
    isCompound: false,
  },
  {
    name: 'Plate Pinch',
    description: 'Grip exercise pinching weight plates',
    exerciseType: 'weighted',
    muscleGroup: 'Forearms',
    equipment: ['weight plates'],
    isCompound: false,
  },
];
